work_dir: ""
raw_data_dir: './train_Data/'
processed_data_dir: './DataSet/processed'
binary_data_dir: './DataSet/binary'
preprocess_cls: configs.datasets.esd.preprocess.ESDPreprocess

binarization_args:
  train_range: [250, -1]
  test_range: [1, 150]
  valid_range: [150, 250]
test_ids: []

mel_vmin: -6
mel_vmax: 1.5

vocoder: HiFiGAN
vocoder_ckpt: checkpoints/pytorch_model.bin
vocoder_cls: models.vocoder.hifigan.HiFiGAN
vocoder_config: configs/models/vocoder/hifigan22k.yaml

num_spk: 1
audio_num_mel_bins: 80
out_dims: 80
audio_sample_rate: 22050  # 16000 → 22050으로 변경
hop_size: 256             # 그대로 유지 (256 samples ≈ 11.6ms at 22kHz)
win_size: 1024            # 그대로 유지
fft_size: 1024            # 그대로 유지
fmin: 0
fmax: 8000                # 보코더 모델명에 맞게 8kHz 유지
f0_min: 80
f0_max: 800

kmeans_model_path: "./models/km200.bin"
hubert_model: "./hubert-base-ls960"

use_spk_encoder: false
lambda_grl: 0.01