base_config:
  - ./base.yaml
task_cls: tasks.vocoder.bigvgan_v2.BigVGANv2Task

# BigVGAN v2 22kHz 아키텍처 설정
resblock: "1"
upsample_rates:
  - 8
  - 8
  - 2
  - 2
upsample_kernel_sizes:
  - 16
  - 16
  - 4
  - 4
upsample_initial_channel: 1536
resblock_kernel_sizes:
  - 3
  - 7
  - 11
resblock_dilation_sizes:
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5

# BigVGAN v2 특화 설정
activation: "snakebeta"
snake_logscale: true
use_weight_norm: false
use_spectral_norm: false

# Discriminator 설정
discriminator: "mrd"
resolutions:
  - - 1024
    - 120
    - 600
  - - 2048
    - 240
    - 1200
  - - 4096
    - 480
    - 2400
  - - 512
    - 50
    - 240
mpd_reshapes:
  - 2
  - 3
  - 5
  - 7
  - 11
discriminator_channel_mult: 1

# Loss 가중치
lambda_adv: 4.0
lambda_mel: 45.0
lambda_feat_match: 2.0
use_fm_loss: true
use_ms_stft: true

# 22kHz에 최적화된 파라미터
generator_lr: 0.0002
discriminator_lr: 0.0002
adam_b1: 0.8
adam_b2: 0.99